#!/usr/bin/env bash

set -o pipefail -o errtrace -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

declare errmsg="ERROR (${0##*/})":
trap 'echo >&2 $errmsg trap on error \(rc=${PIPESTATUS[@]}\) near line $LINENO' ERR

rm -f ~/.config/nvim/init.vim
rm -f ~/.mpprompt
rm -f ~/.bashrc
rm -f ~/.tmux.conf
rm -f ~/.gitconfig
rm -f ~/.macos
rm -f ~/.kubectl-aliases
