#!/usr/bin/env bash

set -o pipefail -o errtrace -o errexit -o nounset
shopt -s inherit_errexit

[[ -n "${TRACE:-}" ]] && set -o xtrace

declare errmsg="ERROR (${0##*/})":
trap 'echo >&2 $errmsg trap on error \(rc=${PIPESTATUS[@]}\) near line $LINENO' ERR

echo "---- Manjaro ----"

readonly aur_dir_path="${HOME}/.custom-aur"

install_from_aur() {
    local pkg
    pkg="$1"
    readonly pkg
    
    if [[ ! -d "${aur_dir_path}/${pkg}" ]]; then
        git clone "https://aur.archlinux.org/${pkg}.git" "${aur_dir_path}/${pkg}"
    fi
    
    pushd "${aur_dir_path}/${pkg}"
    makepkg -csi
    popd
}

sudo pacman -S \
    docker \
    jq \
    maven \
    packer \
    pass \
    pwgen \
    python \
    flake8 \
    the_silver_searcher \
    tmux \
    tree \
    go \
    neovim \
    nodejs \
    npm \
    bash-completion

install_from_aur "google-cloud-sdk"
install_from_aur "jo"

sudo pip install "awscli>=1.14.28,<2.0.0"
sudo pip install --upgrade yq

if ! kubectl version --client=true --short=true | grep --silent --extended-regexp 'v1\.15\.11'; then
    export K8S_VERSION="1.15.11"
    echo " ---> Installing kubectl"
    sudo curl -L -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.11/bin/linux/amd64/kubectl
    sudo chmod 755 /usr/local/bin/kubectl
fi

GO111MODULE="on" go get -u sigs.k8s.io/kind@v0.8.1

if [[ ! -d "${HOME}/.fzf" ]]; then
    echo " ---> Installing fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git "${HOME}/.fzf"
    "${HOME}/.fzf/install"
fi

echo " ---> Installing tmux plugins"
if [[ ! -d "${HOME}/.tmux/plugins/tpm" ]]; then
    git clone https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"
fi
if [[ ! -d "${HOME}/.tmux/plugins/tmux-open" ]]; then
    git clone https://github.com/tmux-plugins/tmux-open.git "${HOME}/.tmux/plugins/tmux-open"
fi
if [[ ! -d "${HOME}/.tmux/plugins/tmux-yank" ]]; then
    git clone https://github.com/tmux-plugins/tmux-yank.git "${HOME}/.tmux/plugins/tmux-yank"
fi
if [[ ! -d "${HOME}/.tmux/plugins/tmux-prefix-highlight" ]]; then
    git clone https://github.com/tmux-plugins/tmux-prefix-highlight.git "${HOME}/.tmux/plugins/tmux-prefix-highlight"
fi

echo " ---> Adding user to docker group"
sudo gpasswd -a "${USER}" docker
sudo usermod -aG docker "${USER}"
sudo systemctl start docker
sudo systemctl enable docker

