#!/usr/bin/env bash

set -o pipefail -o errtrace -o errexit -o nounset

[[ -n "${TRACE:-}" ]] && set -o xtrace

declare errmsg="ERROR (${0##*/})":
trap 'echo >&2 $errmsg trap on error \(rc=${PIPESTATUS[@]}\) near line $LINENO' ERR

cat <<EOF >"${HOME}/.bash_profile"
[[ -f "${HOME}/.bashrc" ]] && . "${HOME}/.bashrc"
[[ -f "${HOME}/.local_bash_profile" ]] && source "${HOME}/.local_bash_profile"
EOF

echo "source /workspaces/.codespaces/.persistedshare/dotfiles/bashrc" >> /home/codespace/.bashrc
