#!/usr/bin/env bash

echo "### MacOS ###"

[ -f ~/.macos ] || ln -s $(PWD)/macos ~/.macos    

cat > "~/.bash_profile" <<EOL
[ -f ~/.bashrc ] && . ~/.bashrc
EOL

which -s brew
if [[ $? != 0 ]]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "installing packages with brew"
brew bundle

read -p "install applications with brew cask? (y/n) " answer
case ${answer:0:1} in
  y|Y )
    echo "installing applications with brew cask"
    ./brew-cask.sh
  ;;
esac

read -p "load macos conf? (y/n) " answer
case ${answer:0:1} in
  y|Y )
    echo "loading macos conf"
    . ~/.macos
  ;;
esac