#!/usr/bin/env bash

echo "### MacOS ###"

[ -f ~/.macos ] || ln -s $(PWD)/macos ~/.macos

cat > "${HOME}/.bash_profile" <<EOL
[ -f ~/.bashrc ] && source ~/.bashrc
EOL

which -s brew
if [[ $? != 0 ]]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

read -p "install programs with brew? (y/n) " answer
case ${answer:0:1} in
  y|Y)
    echo "installing programs with brew"
    brew bundle
esac

read -p "install applications with brew cask? (y/n) " answer
case ${answer:0:1} in
  y|Y )
    echo "installing applications with brew cask"
    brew bundle -f Brewfile-cask
  ;;
esac

read -p "load macos conf? (y/n) " answer
case ${answer:0:1} in
  y|Y )
    echo "loading macos conf"
    . ~/.macos
  ;;
esac
